.onLoad <- function(lib, pkg)
{

  packageStartupMessage("\n")
  packageStartupMessage('ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo')
  packageStartupMessage('o        Geneland is loaded                                       o')
  packageStartupMessage('o                                                                 o')
  packageStartupMessage('o        * Please *                                               o')
  packageStartupMessage('o                                                                 o')  
  packageStartupMessage('o        Register on                                              o')
  packageStartupMessage('o        http://www2.imm.dtu.dk/~gigu/Geneland/register.php       o')
  packageStartupMessage('o                                                                 o')  
  packageStartupMessage('o        See manual on                                            o')
  packageStartupMessage('o        http://www2.imm.dtu.dk/~gigu/Geneland/#Manual            o')  
  packageStartupMessage('o                                                                 o')
  packageStartupMessage('o        Type citation("Geneland") for a quick citation guide     o')
  packageStartupMessage('o                                                                 o') 
  packageStartupMessage('o        See http://www2.imm.dtu.dk/~gigu/Geneland/#              o')
  packageStartupMessage('o        for additional references                                o')
  packageStartupMessage('o                                                                 o')
  packageStartupMessage('o        This is Geneland-4.0.3                                   o')
  packageStartupMessage('o                                                                 o')
  packageStartupMessage('ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo')
}
